#!/usr/bin/env python
# -*- coding:utf-8 -*-

from tkinter import *
import tkinter as ttk
from tkinter import filedialog
import xlrd
import xlwt
import hashlib

root= ttk.Tk()
#root.withdraw()

def md5(str):
    m=hashlib.md5(str.encode("utf8"))
    return m.hexdigest()


def getmd5():
    fname=filedialog.askopenfilename()
    print(fname)
    wb=xlrd.open_workbook(fname)
    table=wb.sheet_by_index(0)
    for i in range(table.nrows):
        result=table.row_values(i)
        item=result.pop(0)
        item=str.upper(md5(item))
        result.insert(0,item)
        num=result.pop(1)
        num=int(num)
        result.insert(1,num)
        result=map(str,result)
        result=','.join(result)
        print(result)
        f = open('/Users/Neo/Desktop/practice/test.txt', 'w')
        f.write(result + '\n')

    return result



Button(root,text='选择文件',width=10,command=getmd5()).grid(row=3,column=1,sticky=E,padx=10,pady=5)

mainloop()


