#!/usr/bin/env python
# -*- coding:utf-8 -*-

from tkinter import *
import tkinter as ttk
from tkinter import filedialog
import xlrd
import xlwt
import hashlib

root= ttk.Tk()
root.title('催收失联修复加密')
root.geometry('200x120+200+200')
#f1=Frame(root);f1.pack()
#f2=Frame(root);f2.pack()


#root.withdraw()

def md5(str):
    m=hashlib.md5(str.encode("utf8"))
    return m.hexdigest()
def getfname():
    fname = filedialog.askopenfilename(filetypes=[("xls","*.xls"),("xlsx","*xlsx")])
    return fname

def getmd5():
    wb=xlrd.open_workbook(fname)
    table=wb.sheet_by_index(0)
    transfer_result = []
    for i in range(table.nrows):
        result=table.row_values(i)
        item=result.pop(0)
        item=str.upper(md5(item))
        result.insert(0,item)
        num=result.pop(1)
        num=int(num)
        result.insert(1,num)
        result=map(str,result)
        result=','.join(result)
        #print(result)
        transfer_result.append(result)
    f = open('/Users/Neo/Desktop/practice/test.txt', 'w')
    for i in range(len(transfer_result)):
        f.write(transfer_result[i] + '\n')
        print(transfer_result[i] + '\n')
    return


#Button(f,text='选择文件',command=getfname).pack(side=LEFT)
#Label(f1,text=fname).pack(side=RIGHT)
#Button(f2,text='加密',command=getmd5).pack(side=LEFT)
Button(root,text='选择文件',width=10,command=getmd5).grid(row=10,column=5,sticky=E,padx=10,pady=5)

mainloop()


